default['postgresql']['prerequisites']['ubuntu'] = %w(git mc joe whois curl libreadline-dev zlib1g-dev bison flex make libssl-dev vim)


default['postgresql']['hba'] = ""


default['postgresql']['config']['data_directory'] = "/opt/pgdata"
default['postgresql']['config']['hba_file']= ""
default['postgresql']['config']['ident_file']=""
default['postgresql']['config']['external_pid_file']=""
default['postgresql']['config']['listen_addresses']=	"*"  
default['postgresql']['config']['port'] = 5432
default['postgresql']['config']['max_connections']= 100 
default['postgresql']['config']['superuser_reserved_connections']= ""
default['postgresql']['config']['unix_socket_directories']= ""
default['postgresql']['config']['unix_socket_group']= ""
default['postgresql']['config']['unix_socket_permissions']= ""
default['postgresql']['config']['bonjour']= ""
default['postgresql']['config']['bonjour_name']= ""
default['postgresql']['config']['authentication_timeout']= ""
default['postgresql']['config']['ssl']= "off"
default['postgresql']['config']['ssl_ciphers']= ""
default['postgresql']['config']['ssl_prefer_server_ciphers']= ""
default['postgresql']['config']['ssl_ecdh_curve']= ""
default['postgresql']['config']['ssl_renegotiation_limit']= ""
default['postgresql']['config']['ssl_cert_file']= ""
default['postgresql']['config']['ssl_key_file']= ""
default['postgresql']['config']['ssl_ca_file']= ""
default['postgresql']['config']['ssl_crl_file']= ""
default['postgresql']['config']['password_encryption']= ""
default['postgresql']['config']['db_user_namespace']= ""
default['postgresql']['config']['krb_server_keyfile']= ""
default['postgresql']['config']['krb_caseins_users']= ""
default['postgresql']['config']['tcp_keepalives_idle']= ""
default['postgresql']['config']['tcp_keepalives_interval']= ""
default['postgresql']['config']['tcp_keepalives_count']= ""
default['postgresql']['config']['shared_buffers']= "128MB"
default['postgresql']['config']['huge_pages']= ""
default['postgresql']['config']['temp_buffers']= ""
default['postgresql']['config']['max_prepared_transactions']= ""
default['postgresql']['config']['work_mem']= ""
default['postgresql']['config']['maintenance_work_mem']= ""
default['postgresql']['config']['autovacuum_work_mem']= ""
default['postgresql']['config']['max_stack_depth']= ""
default['postgresql']['config']['dynamic_shared_memory_type']= "posix"
default['postgresql']['config']['temp_file_limit']= ""
default['postgresql']['config']['max_files_per_process']= ""
default['postgresql']['config']['shared_preload_libraries']= "bdr"
default['postgresql']['config']['vacuum_cost_delay']= ""
default['postgresql']['config']['vacuum_cost_page_hit']= ""
default['postgresql']['config']['vacuum_cost_page_miss']= ""
default['postgresql']['config']['vacuum_cost_page_dirty']= ""
default['postgresql']['config']['vacuum_cost_limit']= ""
default['postgresql']['config']['bgwriter_delay']= ""
default['postgresql']['config']['bgwriter_lru_maxpages']= ""
default['postgresql']['config']['bgwriter_lru_multiplier']= ""
default['postgresql']['config']['effective_io_concurrency']= ""
default['postgresql']['config']['max_worker_processes']= ""
default['postgresql']['config']['wal_level']= "logical"
default['postgresql']['config']['fsync']= ""
default['postgresql']['config']['synchronous_commit']= ""
default['postgresql']['config']['wal_sync_method']= ""
default['postgresql']['config']['full_page_writes']= ""
default['postgresql']['config']['wal_log_hints']= ""
default['postgresql']['config']['wal_buffers']= ""
default['postgresql']['config']['wal_writer_delay']= ""
default['postgresql']['config']['commit_delay']= ""
default['postgresql']['config']['commit_siblings']= ""
default['postgresql']['config']['checkpoint_segments']= ""
default['postgresql']['config']['checkpoint_timeout']= ""
default['postgresql']['config']['checkpoint_completion_target']= ""
default['postgresql']['config']['checkpoint_warning']= ""
default['postgresql']['config']['archive_mode']= ""
default['postgresql']['config']['archive_command']= ""
default['postgresql']['config']['archive_timeout']= ""

default['postgresql']['config']['max_wal_senders']= 4
default['postgresql']['config']['wal_keep_segments']= ""
default['postgresql']['config']['wal_sender_timeout']= ""
default['postgresql']['config']['max_replication_slots']= 6
default['postgresql']['config']['track_commit_timestamp']= "on"
default['postgresql']['config']['synchronous_standby_names']= ""
default['postgresql']['config']['vacuum_defer_cleanup_age']= ""
default['postgresql']['config']['hot_standby']= ""
default['postgresql']['config']['max_standby_archive_delay']= ""
default['postgresql']['config']['max_standby_streaming_delay']= ""
default['postgresql']['config']['wal_receiver_status_interval']= ""
default['postgresql']['config']['hot_standby_feedback']= ""
default['postgresql']['config']['wal_receiver_timeout']= ""

default['postgresql']['config']['enable_bitmapscan']= ""
default['postgresql']['config']['enable_hashagg']= ""
default['postgresql']['config']['enable_hashjoin']= ""
default['postgresql']['config']['enable_indexscan']= ""
default['postgresql']['config']['enable_indexonlyscan']= ""
default['postgresql']['config']['enable_material']= ""
default['postgresql']['config']['enable_mergejoin']= ""
default['postgresql']['config']['enable_nestloop']= ""
default['postgresql']['config']['enable_seqscan']= ""
default['postgresql']['config']['enable_sort']= ""
default['postgresql']['config']['enable_tidscan']= ""

default['postgresql']['config']['seq_page_cost']= ""
default['postgresql']['config']['random_page_cost']= ""
default['postgresql']['config']['cpu_tuple_cost']= ""
default['postgresql']['config']['cpu_index_tuple_cost']= ""
default['postgresql']['config']['cpu_operator_cost']= ""
default['postgresql']['config']['effective_cache_size']= ""

default['postgresql']['config']['geqo']= ""
default['postgresql']['config']['geqo_threshold']= ""
default['postgresql']['config']['geqo_effort']= ""
default['postgresql']['config']['geqo_pool_size']= ""
default['postgresql']['config']['geqo_generations']= ""
default['postgresql']['config']['geqo_selection_bias']= ""
default['postgresql']['config']['geqo_seed']= ""

default['postgresql']['config']['default_statistics_target']= ""
default['postgresql']['config']['constraint_exclusion']= ""
default['postgresql']['config']['cursor_tuple_fraction']= ""
default['postgresql']['config']['from_collapse_limit']= ""
default['postgresql']['config']['join_collapse_limit']= ""

default['postgresql']['config']['log_destination']= ""
default['postgresql']['config']['logging_collector']= "on"
default['postgresql']['config']['log_filename']= "postgresql-%Y-%m-%d_%H%M%S.log"
default['postgresql']['config']['log_file_mode']= ""
default['postgresql']['config']['log_truncate_on_rotation']= ""
default['postgresql']['config']['log_rotation_age']= ""
default['postgresql']['config']['log_rotation_size']= ""
default['postgresql']['config']['syslog_facility']= ""
default['postgresql']['config']['syslog_ident']= ""
default['postgresql']['config']['event_source']= ""
default['postgresql']['config']['client_min_messages']= ""
default['postgresql']['config']['log_min_messages']= ""
default['postgresql']['config']['log_min_error_statement']= ""
default['postgresql']['config']['log_min_duration_statement']= ""

default['postgresql']['config']['debug_print_parse']= ""
default['postgresql']['config']['debug_print_rewritten']= ""
default['postgresql']['config']['debug_print_plan']= ""
default['postgresql']['config']['debug_pretty_print']= ""
default['postgresql']['config']['log_checkpoints']= ""
default['postgresql']['config']['log_connections']= ""
default['postgresql']['config']['log_disconnections']= ""
default['postgresql']['config']['log_duration']= ""
default['postgresql']['config']['log_error_verbosity']= ""
default['postgresql']['config']['log_hostname']= ""
default['postgresql']['config']['log_line_prefix']= "%m"
default['postgresql']['config']['log_lock_waits']= ""
default['postgresql']['config']['log_statement']= "all"
default['postgresql']['config']['log_temp_files']= ""
default['postgresql']['config']['log_timezone']= "US/Central"
default['postgresql']['config']['track_activities']= ""
default['postgresql']['config']['track_counts']= ""
default['postgresql']['config']['track_io_timing']= ""
default['postgresql']['config']['track_functions']= ""
default['postgresql']['config']['track_activity_query_size']= ""
default['postgresql']['config']['update_process_title']= ""
default['postgresql']['config']['stats_temp_directory']= ""
default['postgresql']['config']['log_parser_stats']= ""
default['postgresql']['config']['log_planner_stats']= ""
default['postgresql']['config']['log_executor_stats']= ""
default['postgresql']['config']['log_statement_stats']= ""
default['postgresql']['config']['autovacuum']= ""
default['postgresql']['config']['log_autovacuum_min_duration']= ""
default['postgresql']['config']['autovacuum_max_workers']= ""
default['postgresql']['config']['autovacuum_naptime']= ""
default['postgresql']['config']['autovacuum_vacuum_threshold']= ""
default['postgresql']['config']['autovacuum_analyze_threshold']= ""
default['postgresql']['config']['autovacuum_vacuum_scale_factor']= ""
default['postgresql']['config']['autovacuum_analyze_scale_factor']= ""
default['postgresql']['config']['autovacuum_freeze_max_age']= ""
default['postgresql']['config']['autovacuum_multixact_freeze_max_age']= ""
default['postgresql']['config']['autovacuum_vacuum_cost_delay']= ""
default['postgresql']['config']['autovacuum_vacuum_cost_limit']= ""
default['postgresql']['config']['search_path']=""
default['postgresql']['config']['default_tablespace'] = ""	
default['postgresql']['config']['temp_tablespaces ']= ""
default['postgresql']['config']['check_function_bodies'] = ""
default['postgresql']['config']['default_transaction_isolation'] = ""
default['postgresql']['config']['default_transaction_read_only'] = ""
default['postgresql']['config']['default_transaction_deferrable'] = ""
default['postgresql']['config']['session_replication_role'] = ""
default['postgresql']['config']['statement_timeout'] ="" 			
default['postgresql']['config']['lock_timeout'] = ""
default['postgresql']['config']['vacuum_freeze_min_age'] = ""
default['postgresql']['config']['vacuum_freeze_table_age'] = ""
default['postgresql']['config']['vacuum_multixact_freeze_min_age'] = ""
default['postgresql']['config']['vacuum_multixact_freeze_table_age'] = ""
default['postgresql']['config']['bytea_output'] = ""
default['postgresql']['config']['xmlbinary'] =""
default['postgresql']['config']['xmloption'] =""
default['postgresql']['config']['intervalstyle']=""
default['postgresql']['config']['datestyle'] = "iso, mdy"
default['postgresql']['config']['timezone'] = "US/Central"
default['postgresql']['config']['timezone_abbreviations'] = ""    
default['postgresql']['config']['extra_float_digits'] = ""			
default['postgresql']['config']['client_encoding'] = ""
default['postgresql']['config']['lc_messages'] = 	""		
default['postgresql']['config']['lc_monetary'] = ""			
default['postgresql']['config']['lc_numeric'] = ""
default['postgresql']['config']['lc_time'] = ""
default['postgresql']['config']['default_text_search_config'] = "pg_catalog.english"
default['postgresql']['config']['dynamic_library_path'] = ""
default['postgresql']['config']['local_preload_libraries'] = ""
default['postgresql']['config']['session_preload_libraries'] = ""
default['postgresql']['config']['deadlock_timeout'] = ""
default['postgresql']['config']['max_locks_per_transaction'] = ""
default['postgresql']['config']['max_pred_locks_per_transaction'] = ""	
default['postgresql']['config']['array_nulls'] = ""
default['postgresql']['config']['backslash_quote'] = ""
default['postgresql']['config']['default_with_oids ']= ""
default['postgresql']['config']['escape_string_warning'] = ""
default['postgresql']['config']['lo_compat_privileges ']= ""
default['postgresql']['config']['quote_all_identifiers'] = ""
default['postgresql']['config']['sql_inheritance'] = ""
default['postgresql']['config']['standard_conforming_strings'] = ""
default['postgresql']['config']['synchronize_seqscans'] = ""
default['postgresql']['config']['transform_null_equals'] = ""
default['postgresql']['config']['exit_on_error '] = "" 
default['postgresql']['config']['restart_after_crash '] = ""
default['postgresql']['config']['include_dir'] = ""
default['postgresql']['config']['include_if_exists '] = ""
default['postgresql']['config']['include'] = ""
default['postgresql']['config']['bdr.connections'] = ""
default['postgresql']['config']['bdr.dsnlist'] = ""
















 


 



